name: 'Install Octave (macOS)'
description: 'Install GNU Octave on macOS'
author: 'Ray Zimmerman'

runs:
  using: "composite"
  steps:
    - name: Initialize Package Manager
      run: |
        brew update
        rm -f /usr/local/bin/2to3-3.11
        rm -f /usr/local/bin/idle3.11
        rm -f /usr/local/bin/pydoc3.11
        rm -f /usr/local/bin/python3.11
        rm -f /usr/local/bin/python3.11-config
        echo "HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1" >> $GITHUB_ENV
        echo "HOMEBREW_NO_INSTALL_CLEANUP=1" >> $GITHUB_ENV
      shell: bash

    - name: Install GNU Octave
      run: |
        brew install octave
        echo "ML_NAME=Octave" >> $GITHUB_ENV
        echo "ML_CMD=octave-cli --no-gui --eval" >> $GITHUB_ENV
        echo "ML_PATHVAR=OCTAVE_PATH" >> $GITHUB_ENV
      shell: bash

    - name: Set OCTAVE_VER, ML_VER
      run: |
        export OCTAVE_VER=`$ML_CMD "fprintf('%s', ver('octave').Version)"`
        echo "OCTAVE_VER=${OCTAVE_VER}" >> $GITHUB_ENV
        echo "ML_VER=${OCTAVE_VER}" >> $GITHUB_ENV
      shell: bash

branding:
  icon: 'zap'
  color: 'yellow'
